# Generated by Django 5.0.7 on 2024-11-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_spaceobject_distance_from_earth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaceobject',
            name='created_at',
        ),
    ]
