# Generated by Django 5.0.7 on 2024-11-15 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_spaceobject_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spaceobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='catalog.spaceobject')),
            ],
        ),
    ]
